# Generated by Django 6.0.5 on 2026-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_status_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
