# Generated by Django 6.0.5 on 2026-06-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_schedule_status_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
