# Generated by Django 6.0.5 on 2026-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
